services:
  web:
    container_name: stock-info-app-prod
    build:
      context: .
      dockerfile: Dockerfile       # 기본 Dockerfile (멀티 스테이지) 사용
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: always                # 장애 시 자동 재시작

  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  pgdata:
