export const NASDAQ_100: string[] = [
    "NVDA", "MSFT", "AAPL", "AMZN", "GOOG", "GOOGL", "META", "AVGO",
    "TSLA", "NFLX", "COST", "PLTR", "ASML", "CSCO", "TMUS", "AMD",
    "AZN", "LIN", "INTU", "PEP", "BKNG", "ISRG", "QCOM", "TXN",
    "ARM", "PDD", "AMGN", "SHOP", "ADBE", "HON", "AMAT", "GILD",
    "CMCSA", "PANW", "LRCX", "ADP", "MU", "APP", "VRTX", "MELI",
    "KLAC", "MSTR", "CRWD", "SNPS", "ADI", "SBUX", "INTC", "DASH",
    "CEG", "MDLZ", "CDNS", "CTAS", "ABNB", "ORLY", "FTNT", "MAR",
    "PYPL", "CSX", "ADSK", "WDAY", "MRVL", "CHTR", "REGN", "ROP",
    "AEP", "MNST", "NXPI", "AXON", "FAST", "TEAM", "PCAR", "PAYX",
    "DDOG", "KDP", "CPRT", "CCEP", "ROST", "ZS", "BKR", "EXC",
    "IDXX", "FANG", "TTWO", "XEL", "TTD", "VRSK", "EA", "CSGP",
    "CTSH", "MCHP", "GEHC", "ODFL", "KHC", "DXCM", "WBD", "LULU",
    "ON", "CDW", "GFS", "BIIB", 
]