export const NASDAQ_100: string[] = [
    "NVDA", "MSFT", "AAPL", "AMZN", "GOOG", "GOOGL", "META", "AVGO",
    "TSLA", "NFLX", "COST", "PLTR", "ASML", "CSCO", "TMUS", "AMD",
    "AZN", "LIN", "INTU", "PEP", "BKNG", "ISRG", "QCOM", "TXN",
    "ARM", "PDD", "AMGN", "SHOP", "ADBE", "HON", "AMAT", "GILD",
    "CMCSA", "PANW", "LRCX", "ADP", "MU", "APP", "VRTX", "MELI",
    "KLAC", "MSTR", "CRWD", "SNPS", "ADI", "SBUX", "INTC", "DASH",
    "CEG", "MDLZ", "CDNS", "CTAS", "ABNB", "ORLY", "FTNT", "MAR",
    "PYPL", "CSX", "ADSK", "WDAY", "MRVL", "CHTR", "REGN", "ROP",
    "AEP", "MNST", "NXPI", "AXON", "FAST", "TEAM", "PCAR", "PAYX",
    "DDOG", "KDP", "CPRT", "CCEP", "ROST", "ZS", "BKR", "EXC",
    "IDXX", "FANG", "TTWO", "XEL", "TTD", "VRSK", "EA", "CSGP",
    "CTSH", "MCHP", "GEHC", "ODFL", "KHC", "DXCM", "WBD", "LULU",
    "ON", "CDW", "GFS", "BIIB", 
]

export const SNP_500 : string[] = [
    "NVDA","MSFT","AAPL","AMZN","META","AVGO","GOOGL","GOOG","BRK-B","TSLA",
    "JPM","WMT","V","LLY","ORCL","MA","NFLX","XOM","JNJ","COST",
    "HD","BAC","PLTR","ABBV","PG","CVX","KO","GE","TMUS","UNH",
    "CSCO","AMD","WFC","PM","CRM","MS","ABT","AXP","IBM","GS",
    "LIN","MCD","DIS","RTX","MRK","T","PEP","CAT","UBER","NOW",
    "VZ","INTU","TMO","TXN","BKNG","C","BA","BLK","SCHW","QCOM",
    "ANET","ISRG","SPGI","GEV","ACN","BSX","AMGN","TJX","ADBE","SYK",
    "NEE","DHR","COF","PGR","LOW","PFE","GILD","HON","ETN","BX",
    "MU","APH","UNP","DE","AMAT","PANW","LRCX","CMCSA","KKR","ADI",
    "COP","ADP","MDT","KLAC","NKE","MO","WELL","SNPS","CB","INTC",
    "LMT","CRWD","PLD","DASH","SO","MMC","ICE","VRTX","SBUX","RCL",
    "CEG","PH","CME","BMY","CDNS","AMT","DUK","HCA","CVS","TT",
    "MCO","SHW","WM","ORLY","GD","MCK","CTAS","NOC","MMM","DELL",
    "NEM","PNC","CI","ABNB","MDLZ","AON","TDG","MSI","ECL","COIN",
    "APO","AJG","ITW","EQIX","USB","FI","BK","EMR","UPS","RSG",
    "MAR","ELV","WMB","AZO","HWM","JCI","ZTS","EOG","CL","ADSK",
    "PYPL","APD","HLT","VST","FCX","NSC","WDAY","REGN","URI","TRV",
    "TEL","MNST","CSX","TFC","FTNT","KMI","AEP","NXPI","SPG","AXON",
    "GLW","DLR","AFL","FAST","ROP","COR","CMG","PWR","GM","CARR",
    "BDX","SLB","CMI","MPC","FDX","NDAQ","MET","PSX","SRE","O",
    "ALL","PCAR","LHX","IDXX","PSA","D","DHI","CTVA","PAYX","XYZ",
    "AMP","GWW","CBRE","ROST","OKE","EW","DDOG","VLO","CPRT","OXY",
    "F","GRMN","AIG","KR","BKR","EXC","MSCI","TGT","CCL","CCI",
    "FANG","TTWO","EA","KMB","XEL","AME","EBAY","PEG","YUM","DAL",
    "RMD","MPWR","KVUE","LVS","KDP","ETR","LYV","ROK","PRU","SYY",
    "VMC","CSGP","VRSK","HSY","HIG","MLM","FICO","HUM","FIS","CHTR",
    "TRGP","VICI","A","STX","CAH","ED","CTSH","MCHP","LEN","XYL",
    "WEC","ACGL","NUE","UAL","OTIS","RJF","GEHC","PCG","KHC","WAB",
    "EL","TSCO","STT","IQV","EQT","DD","BRO","WTW","ODFL","IR",
    "MTB","VTR","EXR","EFX","FITB","ADM","BR","HPE","DXCM","WBD",
    "STZ","SYF","DTE","NRG","KEYS","AWK","AVB","WDC","IBKR","K",
    "ROL","IRM","WRB","AEE","PPL","MTD","TTD","HPQ","ATO","EXPE",
    "GIS","VLTO","IP","PHM","HBAN","PTC","VRSN","EQR","TDY","FE",
    "PPG","NTRS","SMCI","SW","CBOE","CNP","DOV","RF","TYL","LULU",
    "STE","DRI","CINF","DG","PODD","ES","TROW","LDOS","WSM","LH",
    "EXE","CPAY","DVN","HUBB","DLTR","CHD","NTAP","CFG","NVR","ULTA",
    "SBAC","JBL","EIX","CDW","GPN","TPL","CMS","KEY","TPR","ZBH",
    "FSLR","GDDY","DGX","ON","TSN","L","NI","AMCR","PKG","LII",
    "BIIB","GPC","HAL","STLD","TRMB","INVH","IT","MKC","TER","WY",
    "CTRA","GEN","ERIE","LYB","FFIV","RL","WAT","PFG","WST","DECK",
    "PNR","J","DOW","ESS","APTV","IFF","LUV","MAA","SNA","BG",
    "LNT","INCY","EVRG","EXPD","FTV","ZBRA","PSKY","TKO","BBY","DPZ",
    "MAS","BLDR","KIM","CHRW","OMC","HOLX","ALLE","CLX","EG","BALL",
    "TXT","CNC","BF-B","FDS","ARE","JBHT","CF","HRL","COO","AVY",
    "BEN","WYNN","REG","UDR","FOX","PAYC","BAX","SOLV","NDSN","FOXA",
    "DOC","IEX","VTRS","CPT","JKHY","HST","SJM","POOL","UHS","SWK",
    "BXP","HAS","AKAM","GL","NCLH","SWKS","NWSA","DAY","AIZ","GNRC",
    "MGM","PNW","HII","MOS","RVTY","ALGN","ALB","AOS","TAP","DVA",
    "IPG","EPAM","MOH","IVZ","AES","CPB","MRNA","KMX","CAG","MTCH",
    "FRT","TECH","HSIC","LKQ","APA","MHK","EMN","CRL","LW","MKTX",
    "NWS","CZR","ENPH"
  ]