import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* 상단 네비게이션 */}
        <nav className="bg-gray-800 text-white p-4 flex gap-4">
          <Link href="/">홈</Link>
          <Link href="/stocks/di20">급락 종목</Link>
        </nav>

        {/* 페이지 컨텐츠 */}
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
